import os
import sys
import numpy as np

# Add app to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.db.vector_store import VectorStore

def seed_brands():
    store = VectorStore()
    
    # Pre-calculated synthetic visual embedding signatures for top targeted brand login templates
    # (In production, these vectors are generated by feeding official brand login screenshots into ResNet50)
    
    np.random.seed(42)
    
    brands = [
        {"name": "sbi", "domain": "sbi.co.in", "seed": 101},
        {"name": "hdfc", "domain": "hdfcbank.com", "seed": 102},
        {"name": "paypal", "domain": "paypal.com", "seed": 103},
        {"name": "google", "domain": "google.com", "seed": 104},
        {"name": "amazon", "domain": "amazon.com", "seed": 105},
        {"name": "microsoft", "domain": "microsoft.com", "seed": 106},
        {"name": "netflix", "domain": "netflix.com", "seed": 107},
        {"name": "icici", "domain": "icicibank.com", "seed": 108}
    ]

    for b in brands:
        # Create deterministic 512-dim embedding vector
        np.random.seed(b["seed"])
        raw_vec = np.random.normal(loc=0.5, scale=0.2, size=512)
        norm_vec = (raw_vec / np.linalg.norm(raw_vec)).tolist()
        
        store.add_brand(
            brand_name=b["name"],
            official_domain=b["domain"],
            vector=norm_vec,
            metadata={"category": "Banking/Tech", "monitored_since": "2026-01-01"}
        )
        print(f"[OK] Seeded brand vector profile: {b['name']} ({b['domain']})")

    print("\n[SUCCESS] All reference brand signatures successfully seeded in VectorStore!")

if __name__ == "__main__":
    seed_brands()
